# Use the vLLM base image
FROM vllm/vllm-openai:nightly-7ed82d1974837957a3bfb6d576b9cffba24d31ae as base

# Install requirements
RUN ln -sf /usr/bin/python3 /usr/bin/python && pip install --no-cache-dir \
    git+https://github.com/huggingface/transformers \
    qwen-vl-utils==0.0.13 \
    torchcodec==0.7 \
    gradio==5.46.1 \
    gradio_client==1.13.1 \
    transformers-stream-generator==0.0.5 \
    accelerate


# Set the command to run vLLM server
CMD ["vllm", "serve", "Qwen/Qwen3-VL-30B-A3B-Instruct", \
     "--host", "0.0.0.0", "--port", "8000", \
     "--trust-remote-code"]
